/* empty css                      */import{S as p,A as w,N as E}from"./assets/vendor-CdjukAW4.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".demo-btn"),i=document.querySelector(".iframe-wrapper"),s=document.getElementById("gameIframe"),c=document.getElementById("closeIframeBtn");!n||!s||!c||!i||(n.addEventListener("click",e=>{e.preventDefault(),s.src=n.dataset.gameUrl,s.classList.add("active"),i.classList.add("active"),c.classList.add("active"),n.style.display="none"}),c.addEventListener("click",()=>{s.src="",s.classList.remove("active"),i.classList.remove("active"),c.classList.remove("active"),n.style.display="block"}))});let f=null,m=null,y=null;const h=1440;function v(){window.innerWidth<h?f||(f=new p(".how-swiper",{modules:[w],loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1},slidesPerView:2,spaceBetween:20})):f&&(f.destroy(!0,!0),f=null)}function L(){window.innerWidth<h?m||(m=new p(".challenge-swiper",{modules:[w],loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1},slidesPerView:2,spaceBetween:10})):m&&(m.destroy(!0,!0),m=null)}function S(){y||(y=new p(".gallery-swiper",{modules:[E,w],loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1},slidesPerView:1,spaceBetween:20,navigation:{nextEl:".gallery-next",prevEl:".gallery-prev"},breakpoints:{1440:{slidesPerView:2}}}))}function I(){v(),L(),S()}window.addEventListener("load",I);window.addEventListener("resize",()=>{v(),L()});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),i=n.querySelector(".icon"),s=document.querySelector(".modal"),c=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const d=`
<svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 33V29.3333H38.5V33H5.5ZM5.5 23.8333V20.1667H38.5V23.8333H5.5ZM5.5 14.6667V11H38.5V14.6667H5.5Z" fill="white" />
</svg>
    `,o=`
<svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M11.7333 34.8333L9.16663 32.2667L19.4333 22L9.16663 11.7333L11.7333 9.16667L22 19.4333L32.2666 9.16667L34.8333 11.7333L24.5666 22L34.8333 32.2667L32.2666 34.8333L22 24.5667L11.7333 34.8333Z" fill="white" />
</svg>
    `;n.addEventListener("click",()=>{t=!t,i.innerHTML=t?o:d,t?r():l()}),c.forEach(u=>u.addEventListener("click",()=>{l(),i.innerHTML=d,t=!1})),window.addEventListener("scroll",a);function r(){s.style.display="block"}function l(){s.style.display="none"}function a(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function i(o){const r=document.getElementById(o);if(!r)return;const l=n(),a=r.getBoundingClientRect().top+window.pageYOffset-l;window.scrollTo({top:a,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(r){const l=this.getAttribute("href");if(!l)return;const[a,u]=l.split("#");if(!u)return;const g=window.location.pathname.split("/").pop();!(a===""||a==="./"||a===g||a==="./"+g)||!document.getElementById(u)||(r.preventDefault(),i(u),t(u))})});const c=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(l=>l.classList.remove("active"));const r=document.querySelector(`.navigation-item a[href*="#${o}"]`);r&&r.closest(".navigation-item").classList.add("active")}function d(){const o=window.pageYOffset+n()+100;c.forEach(r=>{const l=r.offsetTop,a=l+r.offsetHeight;o>=l&&o<a&&t(r.id)})}if(window.addEventListener("scroll",d),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{i(o),t(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),i=document.getElementById("accept-cookies"),s=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});
//# sourceMappingURL=index.js.map
